version: "2"
services:
  mysql:
    build: ./mysql
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=websec
    ports:
    - "3306:3306"
  app:
    build: ./app
    depends_on:
      - mysql
    ports:
      - "5000:5000"